language: ruby
cache: bundler
rvm:
  - 2.2.6

bundler_args: --without production

script:
  - bin/bundle exec rspec spec

notifications:
  email: "snepote@gmail.com"

# safelist
branches:
  only:
  - master
